main: main.Main
name: TTChatSystem
depend: [Essentials, Multiverse-Core, PermissionsEx]
version: 1.0
commands:
  csinfo:
    description: View info about ChatSystem.
  csreload:
    description: Reloads the chat configuration.
    permissions: cs.admin
    usage: /csreload
  cgreload:
    description: Reloads the chat games.
    permissions: cs.admin
    usage: /cgreload
  cgskip:
    description: Skip the current chat game.
    permissions: cg.admin
  cgforce:
    description: Forces the specified chat game to start.
    permissions: cg.admin
    usage: /cgf <name>
  cgenable:
    description: Enable a chat game.
    permissions: cg.admin
    usage: /cgenable <name>
  cgdisable:
    description: Disable a chat game.
    permissions: cg.admin
    usage: /cgdisable <name>
  cgreaction:
    description: Reaction game command.
    permissions: cg.admin
    usage: /cgreaction <add/remove> <word>