main: main.Main
name: TTChatSystem
depend: [Essentials, Multiverse-Core, PermissionsEx]
version: 1.0
commands:
  csinfo:
    description: View info about ChatSystem.
  csreload:
    description: Reloads the chat configuration.
    permission: cs.admin
    usage: /csreload
  cgreload:
    description: Reloads the chat games.
    permission: cs.admin
    usage: /cgreload
  sc:
    description: Staff chat command.
    permission: cs.staffchat
    usage: /sc <message>
  cgskip:
    description: Skip the current chat game.
    permission: cg.admin
  cgforce:
    description: Forces the specified chat game to start.
    permission: cg.admin
    usage: /cgf <name>
  cgenable:
    description: Enable a chat game.
    permission: cg.admin
    usage: /cgenable <name>
  cgdisable:
    description: Disable a chat game.
    permission: cg.admin
    usage: /cgdisable <name>
  cgreaction:
    description: Reaction game command.
    permission: cg.admin
    usage: /cgreaction <add/remove> <word>
  pcc:
    description: Clears your own chat.
