main: me.JustMaffie.TerraTerma.TTChatSystem.Main
name: TTChatSystem
depends: [Essentials, Multiverse-Core, PermissionsEx, TTCore]
version: 0.1
author: JustMaffie
commands:
  setformat:
    description: Set a format for your Chat/Staffchat format